name: CI
on: [push, pull_request]
jobs:
  yamllint:
    name: YAML Lint
    jobs:
      delivery:
        runs-on: ubuntu-latest
        steps:
        - name: Check out code
          uses: actions/checkout@master
        - name: Run yamllint
          uses: actionshub/yamllint@master
  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run prettier
        uses: actionsx/prettier@v2
        with:
          # Prettier CLI arguments
          args: --check "**/*.js"